export const SEARCH_TRACK_BEGIN = "SEARCH_TRACK_BEGIN";
export const SEARCH_TRACK_SUCCESS = "SEARCH_TRACK_SUCCESS";
export const SEARCH_TRACK_FAILURE = "SEARCH_TRACK_FAILURE";

export const SEARCH_ARTIST_BEGIN = "SEARCH_ARTIST_BEGIN";
export const SEARCH_ARTIST_SUCCESS = "SEARCH_ARTIST_SUCCESS";
export const SEARCH_ARTIST_FAILURE = "SEARCH_ARTIST_FAILURE";
